# SPDX-License-Identifier: GPL-2.0+
#
# Makefile - Thrustmaster Force Feedback Wheel driver
#
thrustmaster-ffw-hid-y := thrustmaster-ffw-hid-core.o thrustmaster-ffw-hid-init.o  thrustmaster-ffw-hid-tmff.o
obj-$(CONFIG_THRUSTMASTER_FFW_HID) += thrustmaster-ffw-hid.o
obj-$(CONFIG_THRUSTMASTER_FFW_USB) += thrustmaster-ffw-usb.o

